name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DBT_VERSION: 1.6

    steps:
    - uses: actions/checkout@v3

    - name: Log-in to Docker Hub
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: ./Dockerfile
        context: .
        push: true
        build-args: |
          DBT_VERSION=${{ env.DBT_VERSION }}.*
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/dbt-action:${{ env.DBT_VERSION }}.0
          ${{ secrets.DOCKER_HUB_USERNAME }}/dbt-action
